import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk, Hanken_Grotesk, JetBrains_Mono } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  display: "swap",
});
const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-subspace",
  display: "swap",
});

const JetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap"
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className={`min-h-screen flex flex-col font-body`}>
        {children}
      </body>
    </html>
  );
}
